// fronted-react/src/pages/login.tsx
import '../styles/login.css'

function Login() {

  return (
    <>
        <div className='login-page'>
            <div className="container">
                <div className="image-section"></div>
                <div className="form-section">
                    <div className="form-container">
                        <h2>Welcome Back!</h2>
                        <form>
                            <label htmlFor="email">Email Address</label>
                            <input type="email" id="email" name="email" placeholder="example@mail.com" />
                            {/* <p *ngIf="loginForm.submitted && emailInvalid">Please write the correct email.</p> */}
                            <label htmlFor="password">Password</label>
                            <input type="password" id="password" name="password" placeholder="********" />
                            {/* <p *ngIf="loginForm.submitted && passwordInvalid">Password must be at least 6 characters long.</p> */}
                            <button type="submit">Login</button>
                            {/* <p *ngIf="credentialsError">{{ credentialsError }}</p> */}
                            <div className="signup-link">
                                Don't have an account yet? <a href="/register">Create an account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </>
  )
}

export default Login

// frontend/src/app/login/login.component.ts
import { AfterViewInit, Component, HostListener, Inject, PLATFORM_ID, ViewEncapsulation } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, NgForm, Validators } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { DataService } from '../data.service';
import { ReactiveFormsModule } from '@angular/forms';
import { RouterOutlet } from '@angular/router';
import { Router } from '@angular/router';
import { CommonModule, isPlatformBrowser } from '@angular/common';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [ReactiveFormsModule, HttpClientModule, RouterOutlet, CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers: [DataService],
  encapsulation: ViewEncapsulation.None,
})
export class LoginComponent {
  isAuthenticated: boolean = false;
  loginObj: LoginTemplate;
  credentialsError: string | null = null;
  // message: string = '';

  constructor(
    private fb: FormBuilder, 
    private dataService: DataService, 
    private router: Router, 
  ) {
    this.loginObj = new LoginTemplate();
  }

  login(loginForm: NgForm) {
    console.log(this.loginObj.email);
    if (loginForm.valid) {
      const loginData = { email: this.loginObj.email, password: this.loginObj.password };
      console.log(loginData)
      this.dataService.userLogin(loginData).subscribe({
        next: (response) => {
          console.log('Login successful', response);
          this.router.navigate(['/']);
        },
        error: (error) => {
          if (error.status === 401 && error.error.message === 'Invalid credentials') {
            this.credentialsError = "Неправильне ім'я користувача або пароль";
          } else {
            console.error('Login failed', error);
          }
        },
      });
      // console.log("sfd " + this.authService.getToken());
    }
  }

}

export class LoginTemplate {
  email: string;
  password: string;

  constructor() {
    this.email = "";
    this.password = "";
  }
}
<router-outlet>
    <!-- <div class="background-container">
    </div> -->
    <div class="container">
        <div class="image-section"></div>
        <div class="form-section">
            <div class="form-container">
                <h2>Welcome Back!</h2>
                <form #loginForm="ngForm" (ngSubmit)="login(loginForm)">
                    <label for="email">Email Address</label>
                    <input type="email" id="email" name="email" placeholder="example@mail.com"
                      [(ngModel)]="loginObj.email"
                      minlength="6"
                      required
                      #email="ngModel">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" placeholder="********"
                      [(ngModel)]="loginObj.password"
                      minlength="6"
                      required
                      #password="ngModel">
                    <button type="submit" [disabled]="!loginForm.valid">Login</button>
                    <div class="signup-link">
                        Don't have an account yet? <a href="#">Create an account</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
        
    <!-- <base href="/login/" />
    <div class="login-container">
        <h2>Login</h2>
        <form [formGroup]="loginForm" (ngSubmit)="login()">
            <div class="form-group">
                <label for="username">Username:</label>
                <input id="username" formControlName="username" placeholder="Enter username" />
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input id="password" formControlName="password" type="password" placeholder="Enter password" />
            </div>
            <button type="submit" [disabled]="loginForm.invalid">Login</button>
        </form>
        <p>{{ message }}</p>
    </div> -->
</router-outlet>
